config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find(params[:id])
    @list = List.find(@item[:list_id])
  end

  def new
    @item = Item.new(list_id: params[:list_id])
    @list = List.find(params[:list_id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to list_path(@item.list_id)
    else
      # TODO: error message
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
      redirect_to list_path(@item.list_id)
    else
      redirect_to item_path(@item)
    end
  end

  private

    def item_params
      params.require(:item).permit(:name, :description, :priority, :complete, :list_id)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @items = @list.items
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      #TODO: show confirmation message? or ask if want to add items now?
      redirect_to lists_path
    else
      # TODO: show error message
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      # TODO: error message
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      redirect_to lists_path
    else
      redirect_to list_path(@list)
    end
  end

  private

    def list_params
      params.require(:list).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br />

  <%= f.label :priority %>
  <%= f.select :priority, (1..10) %>
  <br />

  <%= f.label :complete %>
  <%= f.check_box :complete %>
  
  <%= f.hidden_field :list_id %>
  <br />
  <%= f.submit %>

<% end %>

app/views/items/_nav_bar.html.erb
<br />
<%= link_to 'Edit Item', edit_item_path(@item.id) %> |
<%= link_to 'Delete Item', item_path(@item.id), method: :delete, data: {confirm: 'Really delete this item?'} %> 
<hr />
<%= link_to 'Home', root_path %> |
<%= link_to 'Return to List', list_path(@item[:list_id]) %>

app/views/items/edit.html.erb
<h1>Edit <%= @item.name %> </h1>
<hr />
<%= render(partial: 'form') %>

<br />
<%= render(partial: 'nav_bar') %>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Add New Item to <%= @list.name %></h1>
<hr />
<%= render(partial: 'form') %>

<hr />
<%= link_to 'Home', root_path %> |
<%= link_to 'Return to List', list_path(@list.id) %>

app/views/items/show.html.erb
<h1>Item <%= @item.name %> in <%= @list.name %></h1>
<hr />
<h2> Description </h2>
<%= @item.description %>
<h3> Priority </h3>
<%= @item.priority %>
<h3> Completed? </h3>
<%= @item.complete %> 
<br />

<%= render(partial: 'nav_bar') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheRealTodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/lists/_nav_bar.html.erb
<hr />
<%= link_to 'Home', root_path %> |
<%= link_to 'Add New List', new_list_path %>

app/views/lists/edit.html.erb
<h1>Edit <%= @list.name %> </h1>
<hr />
<%= render(partial: 'form') %>
<br />
<%= render(partial: 'nav_bar') %>

app/views/lists/index.html.erb
<h1>All the Lists</h1>
<hr />
<% if @lists.any? %> 
  <ul>
    <% @lists.each do |list| %>
      <li>
        <%= link_to list.name, list_path(list) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <h3>There are no visible lists</h3>
<% end %>
<br />
<%= render(partial: 'nav_bar') %>

app/views/lists/new.html.erb
<h1>Create a New List</h1>
<hr />
<%= render(partial: 'form') %>
<br />
<%= render(partial: 'nav_bar') %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<hr />
<% if @items.any? %>
  <ul>
    <% @items.each do |item| %>
      <li>
        <%= link_to item.name, item_path(item) %>
      </li>
    <% end %>
  </ul>

<% else %>
  <h3>There are no items in this list</h3>
<% end %>

<%= link_to 'Create New Item', new_item_path(list_id: @list.id) %> |
<%= link_to 'Edit List Name', edit_list_path(@list) %> |
<%= link_to 'Delete List', list_path(@list.id), method: :delete, data: {confirm: 'Really delete this item?'} %>
<br />

<%= render(partial: 'nav_bar') %>